"""empty message

Revision ID: c24c843127e7
Revises: 4ac6a3f95d3f
Create Date: 2020-11-01 18:50:33.649596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24c843127e7'
down_revision = '4ac6a3f95d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_venue_name_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_name'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_venue_name_fkey', 'Show', 'Artist', ['venue_name'], ['name'])
    # ### end Alembic commands ###
